[package]
name = "day02"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"

[[bin]]
name = "day02"
path = "src/main.rs"

[dependencies]
criterion = "0.5.1"
itertools = "0.13.0"

[[bench]]
name = "benchmark"
harness = false
