[package]
name = "day05"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"

[[bin]]
name = "day05"
path = "src/main.rs"

[dependencies]
criterion = "0.5.1"
rayon = "1.10.0"

[[bench]]
name = "benchmark"
harness = false
